// <auto-generated />
using Adigabze.Data.Concrete.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Adigabze.WebUI.Migrations
{
    [DbContext(typeof(AdigabzeContext))]
    [Migration("20190409173019_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Adigabze.Entity.Kazanim", b =>
                {
                    b.Property<int>("KazanimId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama");

                    b.Property<string>("KazanimTanim");

                    b.Property<int>("KonuId");

                    b.HasKey("KazanimId");

                    b.HasIndex("KonuId");

                    b.ToTable("Kazanimlar");
                });

            modelBuilder.Entity("Adigabze.Entity.Konu", b =>
                {
                    b.Property<int>("KonuId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KonuTanim");

                    b.Property<int>("UniteId");

                    b.HasKey("KonuId");

                    b.HasIndex("UniteId");

                    b.ToTable("Konular");
                });

            modelBuilder.Entity("Adigabze.Entity.Unite", b =>
                {
                    b.Property<int>("UniteId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UniteTanim");

                    b.Property<int>("YetkinlikId");

                    b.HasKey("UniteId");

                    b.HasIndex("YetkinlikId");

                    b.ToTable("Uniteler");
                });

            modelBuilder.Entity("Adigabze.Entity.Yetkinlik", b =>
                {
                    b.Property<int>("YetkinlikId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("YetkinlikTanim");

                    b.HasKey("YetkinlikId");

                    b.ToTable("Yetkinlikler");
                });

            modelBuilder.Entity("Adigabze.Entity.Kazanim", b =>
                {
                    b.HasOne("Adigabze.Entity.Konu", "Konu")
                        .WithMany("Kazanimlar")
                        .HasForeignKey("KonuId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Adigabze.Entity.Konu", b =>
                {
                    b.HasOne("Adigabze.Entity.Unite", "Unite")
                        .WithMany("Konular")
                        .HasForeignKey("UniteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Adigabze.Entity.Unite", b =>
                {
                    b.HasOne("Adigabze.Entity.Yetkinlik", "Yetkinlik")
                        .WithMany("Uniteler")
                        .HasForeignKey("YetkinlikId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
