// <auto-generated />
using System;
using Adigabze.Data.Concrete.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Adigabze.Data.Migrations
{
    [DbContext(typeof(AdigabzeContext))]
    partial class AdigabzeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Adigabze.DAL.Entities.Anahtar", b =>
                {
                    b.Property<int>("AnahtarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnahtarId"));

                    b.Property<int>("MyProperty")
                        .HasColumnType("int");

                    b.Property<string>("Sozcuk")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnahtarId");

                    b.ToTable("Dizin");
                });

            modelBuilder.Entity("Adigabze.DAL.Entities.Boy", b =>
                {
                    b.Property<int>("BoyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BoyId"));

                    b.Property<string>("BoyAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DilId")
                        .HasColumnType("int");

                    b.HasKey("BoyId");

                    b.HasIndex("DilId");

                    b.ToTable("Boy");
                });

            modelBuilder.Entity("Adigabze.DAL.Entities.Dil", b =>
                {
                    b.Property<int>("DilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DilId"));

                    b.Property<string>("DilAd")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DilId");

                    b.ToTable("Diller");
                });

            modelBuilder.Entity("Adigabze.DAL.Entities.Harf", b =>
                {
                    b.Property<int>("HarfId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HarfId"));

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyukHarf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DilId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KucukHarf")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HarfId");

                    b.HasIndex("DilId");

                    b.ToTable("Alfabe");
                });

            modelBuilder.Entity("Adigabze.DAL.Entities.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("ImageId");

                    b.HasIndex("ParentId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Adigabze.DAL.Entities.ImageEvaluation", b =>
                {
                    b.Property<int>("ImageEvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageEvaluationId"));

                    b.Property<int>("Evaluation")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ImageEvaluationId");

                    b.HasIndex("UserId");

                    b.ToTable("ImageEvaluations");
                });

            modelBuilder.Entity("Adigabze.DAL.Entities.Kazanim", b =>
                {
                    b.Property<int>("KazanimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KazanimId"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KazanimTanim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KonuId")
                        .HasColumnType("int");

                    b.HasKey("KazanimId");

                    b.HasIndex("KonuId");

                    b.ToTable("Kazanimlar");
                });

            modelBuilder.Entity("Adigabze.DAL.Entities.Konu", b =>
                {
                    b.Property<int>("KonuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KonuId"));

                    b.Property<string>("KonuTanim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UniteId")
                        .HasColumnType("int");

                    b.HasKey("KonuId");

                    b.HasIndex("UniteId");

                    b.ToTable("Konular");
                });

            modelBuilder.Entity("Adigabze.DAL.Entities.Lehce", b =>
                {
                    b.Property<int>("LehceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LehceId"));

                    b.Property<int>("DilId")
                        .HasColumnType("int");

                    b.Property<string>("LehceAd")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LehceId");

                    b.HasIndex("DilId");

                    b.ToTable("Lehce");
                });

            modelBuilder.Entity("Adigabze.DAL.Entities.Parent", b =>
                {
                    b.Property<int>("ParentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParentId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Evaluation")
                        .HasColumnType("tinyint");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileNameO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Magnitute")
                        .HasColumnType("int");

                    b.Property<int>("Scale")
                        .HasColumnType("int");

                    b.HasKey("ParentId");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("Adigabze.DAL.Entities.Sozcuk", b =>
                {
                    b.Property<int>("SozcukId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SozcukId"));

                    b.Property<int>("AnahtarId")
                        .HasColumnType("int");

                    b.Property<string>("Anlam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KokId")
                        .HasColumnType("int");

                    b.Property<int>("SozcukTuru")
                        .HasColumnType("int");

                    b.Property<int?>("YetkinlikID")
                        .HasColumnType("int");

                    b.HasKey("SozcukId");

                    b.HasIndex("AnahtarId");

                    b.HasIndex("KokId");

                    b.HasIndex("YetkinlikID");

                    b.ToTable("Sozluk");
                });

            modelBuilder.Entity("Adigabze.DAL.Entities.SozcukEk", b =>
                {
                    b.Property<int>("SozcukEkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SozcukEkId"));

                    b.Property<string>("Ek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EkTipi")
                        .HasColumnType("int");

                    b.Property<int>("EkTuru")
                        .HasColumnType("int");

                    b.Property<string>("Tanim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UstId")
                        .HasColumnType("int");

                    b.HasKey("SozcukEkId");

                    b.HasIndex("UstId");

                    b.ToTable("Ekler");
                });

            modelBuilder.Entity("Adigabze.DAL.Entities.Sulale", b =>
                {
                    b.Property<int>("SulaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SulaleId"));

                    b.Property<int>("BoyId")
                        .HasColumnType("int");

                    b.Property<string>("SulaleAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SulaleId");

                    b.HasIndex("BoyId");

                    b.ToTable("Sulaleler");
                });

            modelBuilder.Entity("Adigabze.DAL.Entities.Unite", b =>
                {
                    b.Property<int>("UniteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UniteId"));

                    b.Property<string>("UniteTanim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YetkinlikId")
                        .HasColumnType("int");

                    b.HasKey("UniteId");

                    b.HasIndex("YetkinlikId");

                    b.ToTable("Uniteler");
                });

            modelBuilder.Entity("Adigabze.DAL.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("EMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Adigabze.DAL.Entities.Yetkinlik", b =>
                {
                    b.Property<int>("YetkinlikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YetkinlikId"));

                    b.Property<string>("YetkinlikTanim")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("YetkinlikId");

                    b.ToTable("Yetkinlikler");
                });

            modelBuilder.Entity("Adigabze.DAL.Entities.Boy", b =>
                {
                    b.HasOne("Adigabze.DAL.Entities.Dil", "Dil")
                        .WithMany()
                        .HasForeignKey("DilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dil");
                });

            modelBuilder.Entity("Adigabze.DAL.Entities.Harf", b =>
                {
                    b.HasOne("Adigabze.DAL.Entities.Dil", "Dil")
                        .WithMany("Alfabe")
                        .HasForeignKey("DilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dil");
                });

            modelBuilder.Entity("Adigabze.DAL.Entities.Image", b =>
                {
                    b.HasOne("Adigabze.DAL.Entities.Parent", "Parent")
                        .WithMany("Images")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Adigabze.DAL.Entities.ImageEvaluation", b =>
                {
                    b.HasOne("Adigabze.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Adigabze.DAL.Entities.Kazanim", b =>
                {
                    b.HasOne("Adigabze.DAL.Entities.Konu", "Konu")
                        .WithMany("Kazanimlar")
                        .HasForeignKey("KonuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Konu");
                });

            modelBuilder.Entity("Adigabze.DAL.Entities.Konu", b =>
                {
                    b.HasOne("Adigabze.DAL.Entities.Unite", "Unite")
                        .WithMany("Konular")
                        .HasForeignKey("UniteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unite");
                });

            modelBuilder.Entity("Adigabze.DAL.Entities.Lehce", b =>
                {
                    b.HasOne("Adigabze.DAL.Entities.Dil", "Dil")
                        .WithMany("Lehceler")
                        .HasForeignKey("DilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dil");
                });

            modelBuilder.Entity("Adigabze.DAL.Entities.Sozcuk", b =>
                {
                    b.HasOne("Adigabze.DAL.Entities.Anahtar", "AnahtarSozcuk")
                        .WithMany()
                        .HasForeignKey("AnahtarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adigabze.DAL.Entities.Anahtar", "Kok")
                        .WithMany()
                        .HasForeignKey("KokId");

                    b.HasOne("Adigabze.DAL.Entities.Yetkinlik", "Yetkinlik")
                        .WithMany()
                        .HasForeignKey("YetkinlikID");

                    b.Navigation("AnahtarSozcuk");

                    b.Navigation("Kok");

                    b.Navigation("Yetkinlik");
                });

            modelBuilder.Entity("Adigabze.DAL.Entities.SozcukEk", b =>
                {
                    b.HasOne("Adigabze.DAL.Entities.SozcukEk", "Temel")
                        .WithMany()
                        .HasForeignKey("UstId");

                    b.Navigation("Temel");
                });

            modelBuilder.Entity("Adigabze.DAL.Entities.Sulale", b =>
                {
                    b.HasOne("Adigabze.DAL.Entities.Boy", "Boy")
                        .WithMany("Sulaleler")
                        .HasForeignKey("BoyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boy");
                });

            modelBuilder.Entity("Adigabze.DAL.Entities.Unite", b =>
                {
                    b.HasOne("Adigabze.DAL.Entities.Yetkinlik", "Yetkinlik")
                        .WithMany("Uniteler")
                        .HasForeignKey("YetkinlikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Yetkinlik");
                });

            modelBuilder.Entity("Adigabze.DAL.Entities.Boy", b =>
                {
                    b.Navigation("Sulaleler");
                });

            modelBuilder.Entity("Adigabze.DAL.Entities.Dil", b =>
                {
                    b.Navigation("Alfabe");

                    b.Navigation("Lehceler");
                });

            modelBuilder.Entity("Adigabze.DAL.Entities.Konu", b =>
                {
                    b.Navigation("Kazanimlar");
                });

            modelBuilder.Entity("Adigabze.DAL.Entities.Parent", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Adigabze.DAL.Entities.Unite", b =>
                {
                    b.Navigation("Konular");
                });

            modelBuilder.Entity("Adigabze.DAL.Entities.Yetkinlik", b =>
                {
                    b.Navigation("Uniteler");
                });
#pragma warning restore 612, 618
        }
    }
}
